CODE_OF_CONDUCT.rst, CONTRIBUTING.rst, LICENSE, README.rst, docs/source/devel/code_of_conduct.rst, docs/source/devel/contributing.rst, docs/source/devel/development.rst, docs/source/devel/index.rst
- Code of Conduct
- Contributing
That documentation also are linked to the docs/ (Sphinx).
=> Additional documentation for development

.github/workflows/ci.yml, .github/workflows/functional.yml, .github/workflows/lint.yml, tests/functional/bootstrap/test_bootstrap.py
- Test lint for PR
- Fixed lints
- Fix ci.yml paths
=> build: improve the workflows distributions/trigger

.github/workflows/ci.yml
The following PR removes a secret that is no longer used in the functional.yml file and thus fixes the issue with our CI. 
It also adds the submodule locations to the trigger paths. 
Fixes #98 
=> fix: remove obsolete secret and fix CI yml file formatting

.github/workflows/ci.yml
The following PR updates the path conditions used by CI.yml so we run the functional tests whenever there's an update found in the git submodules.
=> build: update path trigger conditions in CI.yml

.github/workflows/ci.yml, .github/workflows/update-submodules.yml
The following PR update the CI to run for every PR
Fixes #136
=> chore: run CI for every PR

docs/source/guide/introduction/introduction.rst
We update a few items in the introduction.rst file (e.g., spelling, grammar, word choice).
=> Fix typos in the introduction.rst

.github/workflows/ci.yml
The following PR updates the CI to run for every PR
Related to https://github.com/vmware/repository-service-tuf/issues/136
=> chore: simplify CI.yml rules

tests/features/tokens/login.feature, tests/functional/conftest.py, tests/functional/tokens/test_login.py
Implement Feature BDD file for Token Login.
This Feature covers different Scenarios for the Token Login endpoint:
- Using login directly using API calls
- Using rstuf-cli login
Task 2/3 for #132 
=> Implement Feature BDD file for Token Login

docs/source/guide/introduction/introduction.rst
As spotted by review of https://github.com/vmware/repository-service-tuf-cli/pull/137
=> Fix small typo in tokens

docs/source/devel/development.rst
This commits add the documentation about the Functional Tests (BDD) and the process for Feature request/proposal.
Also add simple explanation about general UT and toolings.
Closes #52
=> Add to development process FT and Feature request

ROADMAP.rst
Fix links in ROADMAP.
Closes https://github.com/vmware/repository-service-tuf/issues/137
=> Fix links in ROADMAP

tests/features/targets/import_targets.feature
- This commit adds the gherkin Feature file for the #188
- This follows the Feature process described on https://repository-service-tuf.readthedocs.io/en/latest/devel/development.html#rstuf-feature
=> Feature: FT for import targets to RSTUF DB

ROADMAP.rst
- Update Issue #28 in the Roadmap
=> Roadmap update: Issue #28

docs/source/guide/deployment/all_in_one.rst, docs/source/guide/deployment/importing-targets.rst, docs/source/guide/index.rst
Add a chapter with more details about using the load data feature from the CLI
Closes #226
=> Add load data information to the Guide

ROADMAP.rst
Mark "Data load for migrations" as complete as #188 is closed.
=> Mark "Data load for migrations" as complete

ROADMAP.rst
Add to the Minimum Working Version board to the ROADMAP.
=> Add the MWV Board

.github/workflows/functional.yml, ROADMAP.rst, docs/source/devel/development.rst, docs/source/guide/deployment/docker-compose.yml
Rename ghcr.io/vmware to ghcr.io/repository-service-tuf
=> Rename GitHub infrastructure

.github/workflows/functional.yml
Remove deprecated environment variable for RSTUF API deployment.
=> Remove deprecated environment variable for API

ROADMAP.rst
This add last updates to ROADMAP after beta release
=> Update ROADMAP after beta release

docs/source/index.rst
Update the short RSTUF vide in the landing page:
- Fix English
- Update the logo
- Small animation fixes
=> Update the short RSTUF video

tests/features/targets/performance.feature, tests/functional/conftest.py, tests/functional/targets/test_performance.py
RSTUF introduced a new standardazied task result status.
The new standard uses a boolen value for status.
=> test: update FT to use new task status

docs/source/guide/general/usage.rst
Add usage doc for metadata update.
Closes [#317 ](https://github.com/repository-service-tuf/repository-service-tuf-cli/issues/317)
=> Add usage doc for metadata update

Pipfile, Pipfile.lock, requirements.txt
The package was removed on this build PR
https://github.com/repository-service-tuf/repository-service-tuf/pull/447/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552
It caused a broken FT
=> Fix the broken FT due missing 'py' package

TAC.rst
as suggested by @kairoaraujo :pray:
=> @simi's proposal to join TAC

.github/workflows/ci.yml
Do not run Functional Tests when the PR is related to docs
=> Exclude from CI when docs/**

.github/workflows/functional.yml
- fallback to dev images by default to keep the original behaviour
=> Use inputs in functional workflow.

.github/workflows/FT-das.yml
Update DAS Functional Tests with the new question from CLI:
"Do you still want to sign root? [y/n]"
=> Update DAS to new signing process questions

README.rst, docs/source/index.rst
----
:books: Documentation preview :books:: https://repository-service-tuf--543.org.readthedocs.build/en/543/
=> Small language edits Patch 1

ROADMAP.rst
This update is based on the discussion at the Community Meeting done on 1/No/2023
https://docs.google.com/document/d/13a_AtFpPK9WO4PlAN6ciD-G1jiBU3gEDtRD1OUinUFY/edit#heading=h.nwyt40krxzp2
----
:books: Documentation preview :books:: https://repository-service-tuf--547.org.readthedocs.build/en/547/
=> Update ROADMAP.rst from Community Meetings 1/Nov/2023

tests/functional/metadata/test_update.py
Make sure we stop the process of running requests to the API server when there is an exception.
I tried to cover most if not all of the cases where I expected possible exceptions.
If new exceptions appear we can modify this test file again.
=> Fail fast on metadata update func tests error

tests/functional/bootstrap/test_bootstrap.py, tests/functional/targets/test_performance.py
=> Fix linting issues

Makefile
Fix functional test searching in the wrong dir
=> Fix functional test searching in wrong dir

tests/functional/artifacts/test_performance.py, tests/functional/conftest.py
Makes FT compatible with new datetime call
=> fix: utcnow on FT

tests/functional/scripts/rstuf-admin-metadata-sign.py, tests/functional/scripts/run-ft-das.sh
Prepare ft tests for new rstuf admin sign features.
=> Prepare ft tests for new rstuf admin sign features

tests/functional/scripts/rstuf-admin-ceremony.py, tests/functional/scripts/rstuf-admin-metadata-sign.py, tests/functional/scripts/rstuf-admin-metadata-update.py, tests/functional/scripts/run-ft-das.sh, tests/functional/scripts/run-ft-signed.sh
Add the new CLI selection interface to the Functional Tests
=> test: FT using new selection interface

tests/functional/scripts/run-ft-das.sh
The same dic key name in the script make it add JoeCocker key as online key To avoid duplicated I added a comment as `extra key`
=> fix: FT using CLI with select for DAS

tests/features/bootstrap/bootstrap.feature, tests/functional/bootstrap/test_bootstrap.py
Remove legacy usage for FT using for bootstrap using CLI
=> test: fix bootstrap FT

tests/functional/scripts/rstuf-admin-metadata-update.py
Fix functional tests to make it compatible with changes from https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/636/
=> tests: ft fix FT to be compatible to new CLI (#636)

ROADMAP.rst, docs/source/guide/deployment/guide/helm.rst, docs/source/guide/deployment/guide/helm/values.yaml, docs/source/guide/deployment/guide/kubernetes.rst, docs/source/guide/deployment/guide/quick-start.rst, docs/source/guide/deployment/index.rst, docs/source/guide/deployment/planning/deployment.rst, docs/source/guide/deployment/setup.rst, docs/source/guide/general/usage.rst, docs/source/guide/index.rst, docs/source/index.rst
Update the RSTUF documentation for the 1.0.0 beta changes
----
📚 Documentation preview 📚: https://repository-service-tuf--825.org.readthedocs.build/en/825/
=> Update docs 1.0.0 beta

tests/functional/scripts/rstuf-admin-ceremony.py, tests/functional/scripts/rstuf-admin-metadata-sign.py, tests/functional/scripts/rstuf-admin-metadata-update.py, tests/functional/scripts/run-ft-das.sh, tests/functional/scripts/run-ft-signed.sh
This PR is intent to support https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/712/
=> tests: adjust ft to support cli pr #712

tests/functional/scripts/rstuf-admin-ceremony.py, tests/functional/scripts/rstuf-admin-metadata-sign.py, tests/functional/scripts/rstuf-admin-metadata-update.py
Fix FT for https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/750
This PR introduces the headers in the settings
=> tests: fix ft for rstuf-cli #750 (headers)

tests/functional/metadata/test_update.py, tests/functional/scripts/run-ft-das-cdr.sh, tests/functional/scripts/run-ft-das.sh, tests/functional/scripts/run-ft-signed.sh
Add support to FT with new select question after choosing wich offline key to sign (ceremony or update)
- https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/805
=> test: FT to support new CLI PR 805 (New select question)

CONTRIBUTING.rst
Add more details for the first time contributors.
----
📚 Documentation preview 📚: https://repository-service-tuf--867.org.readthedocs.build/en/867/
=> docs: Contributing

.github/workflows/update-submodules.yml
Fix failure, adding python 3.13
=> fix: update-submodules.yml adding 3.13
