repository-service-tuf/repository-service-tuf

- .github/workflows/ci.yml
- .gitmodules
Moving submodules from ssh/git to https.
The readthedocs.org doesn't support submodules as ssh/git
https://readthedocs.org/projects/tuf-repository-service/
Also, trying to pass the token to functional.yml -- will not be a problem when the GitHub Packages Registry for RSTUF becomes public.
> Move submodules from ssh/git to https rtfd.io

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/ISSUE_TEMPLATE/other.yml
- .github/ISSUE_TEMPLATE/task.yml
- .github/PULL_REQUEST_TEMPLATE/pr.yml
The following PR adds templates for both issues and pull requests. 
It is based on the beta feature of Github to use yml issue forms which contribute to a better user experience - ref. [github/creating-issue-forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)
**Note:**
This PR has all of the issues included so we can review them at once. When we approve their format, I'll update this one and create follow-up PRs in the other repositories so we have only the templates that are relevant to each repository.
> chore: create Github yml templates for issues and pull requests

- .github/workflows/update-python-deps.yml
The following PR adds a dedicated workflow for updating Python dependencies. 
Details:
* Runs daily
* If another one is already opened, it doesn't create a new one, instead, it updates it.
Fixes https://github.com/vmware/repository-service-tuf/issues/84
> build: add workflow for updating python dependencies

- .github/workflows/functional.yml
- tests/functional/bootstrap/test_bootstrap.py
- tests/functional/conftest.py
The current logic fails because the if `cli_version` is different of 'dev' it will try to install twice the 'latest' and there is no branch latest.
It looks for some specific tag/branch when it starts with 'v'
- Dynaconf[ini] still needed to be installed explicity (https://github.com/vmware/repository-service-tuf-cli/issues/119)
- Made the assert error return more explict in case for rc code tests
> fix: condition to correct get vX.Y.Z

- .github/workflows/functional.yml
It simplifies the GHA workflow to use the git clone instead of the submodules. It enables when used as ``workflow_call`` by other workflows and does not require the submodule.
The submodule is still required in the umbrella to handle the documentation builds.
> Simplify functional

- CONTRIBUTING.rst
- README.rst
- docs/source/guide/overview/overview.rst
- docs/source/index.rst
I was asked to do an editorial pass over the landing docs for RSTUF. I hope this isn't too heavy-handed?
It may be worth consolidating README and OVERVIEW in future and including [fragments](https://docutils.sourceforge.io/docs/ref/rst/directives.html#including-an-external-document-fragment) of README in OVERVIEW, right now the content feels similar.
> Heavy editorial pass over landing docs

- .github/workflows/update-submodules.yml
The following PR adds a cron job for daily syncing the references to the submodules and opens a PR in case there's an update.
> build: add cron job for daily sync of git submodules

- .github/workflows/update-python-deps.yml
- .github/workflows/update-submodules.yml
The following PR sets specific names for our automated PR process of updating dependencies and syncing submodules.
Fixes #109 
> fix: choose specific names for automated PRs

- tests/features/targets/add_targets.feature
This is the first step toward resolving the issue https://github.com/vmware/repository-service-tuf/issues/47.
The feature file follows the [Gherkin](https://cucumber.io/docs/gherkin/reference/) language.
> Create the "add targets" API call feature file 

- .github/workflows/functional.yml
This makes the FT tests and the local development deployment use the same password for the admin.
Makes easier for developers that are running functional tests locally.
Closes #141
> Move FT tests admin password to secret.

- .github/workflows/update-submodules.yml
Go back to running the functional tests before updating the submodules. 
This is not optimal yet because it actually uses the `dev` tagged images and do not build the images on the go based on the actual references, but it will be enough for the time being to check whether it make sense to proceed with updating the submodules. 
The proposed solution is to build and tag images based on the content of the referenced submodules, then run the functional tests against those images.
Related to #150
> build: update of update-submodules.yml

- tests/functional/bootstrap/test_bootstrap.py
- tests/functional/conftest.py
It prevents errors when the shell output from CLI shows some scapes and the assert will fail.
- Fix the assert with 'or'
> Remove the ANSI C1 scape sequence

- .github/workflows/functional.yml
Add the generated payload.json to the rstuf-umbrella path it exists.
It is required by the BDD tests as the `make` command will run from another target folder.
> build: add the generated payload.json umbrella

- tests/features/targets/remove_targets.feature
- tests/functional/conftest.py
- tests/functional/targets/test_add_targets.py
- tests/functional/targets/test_remove_targets.py
The main changes of this pr are:
- added remove targets feature file with scenarios description
- added functional tests for the remove targets feature file
- added improvements in contests that simplified test_add_targets.py functional tests as well
- simplified the test_add_targets.py functional tests
Note: In the second scenario `Removing targets that do exist and ignoring the rest` in test_remove_targets.py I am reusing fixtures (steps) defined from the first scenario.
I reused some of the `given` and `then` steps.
> Add remove targets feature and functional tests + improvements

- docs/source/guide/deployment/all_in_one.rst
Fixing a few typos that were discovered while reading the docs.
> Fix typos in "All-in-one" docs section

- README.rst
Add the OpenSSF Best Practices badge to RSTUF umbrella README.rst (it adds also to RSTUF documentation)
> Add OpenSSF Best Practices badge

- ROADMAP.rst
- Added to the MWV the Roles Simplification features
- Removed feature, that doesn't impact the minimum functionalities
- Add TLS/SSL for Broker and Result Backend communication (Issue #6): It can be achivied by not exposing the Broker and Result Backend communication.
- Moved features that are not compatibility breaker to MVP
- Old Metadata retention
- Support to AWS S3 (Storage) and AWS KMS (Key Vault)
- Token revocation
- Fixed components milestone/versions
- MWV: v1.0.0bX
- MVP: v1.0.X
> Update the ROADMAP

- MAINTAINERS.rst
Given that each component maintainer contributes to the overall project maintenance,
this PR adds all component maintainers in the umbrella repository `MAINTAINERS.rst`.
> RSTUF umbrella repository list all maintainers

- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/functional.yml
- .gitmodules
- CONTRIBUTING.rst
- ROADMAP.rst
- docs/source/devel/development.rst
It is part of the process moving RSTUF to OpenSSF organization.
> Move RSTUF to github.com/repository-service-tuf

- .github/workflows/functional.yml
This commit just enforces or make explicit that RSTUF deployment for FT test uses the built-in authentication/authorization.
> Force RSTUF to use built-in auth on FT

- .github/workflows/ci.yml
- .github/workflows/functional.yml
- .github/workflows/update-submodules.yml
In order for other workflows call the `functional.yml` workflow it is required to receive the secrets for the `RSTUF_ONLINE_KEY`.
- Updated the `.github/workflows/ci.yml`
- Updated the `.github/workflows/update-submodules.yml`
> FT workflow_call requires secrets

- .github/workflows/functional.yml
- tests/functional/bootstrap/test_bootstrap.py
- tests/functional/conftest.py
As implemented by CLI
(https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/289) the functional tests require to use the `--auth` parameters to be compatible with the existent tests, these tests use a API running the built-in authentication.
Note: We are planning changing the FT to be compatible with issue #41 This commit doesn't aim this change. It fix the current state.
> Functional tests uses `RSTUF CLI` with `--auth`

- ROADMAP.rst
Update RSTUF roadmap closing the feature: Option to Disable the API Authentication/Authorization.
The feature was closed by issue #282 which implemented a mechanism to enable/disable the Auth.
Issue #41 was renamed to: Refactoring Authentication/Authorization as an API service. It contains multiple tasks, including #282 which was closed.
> Update ROADMAP.rst feature finished: disable auth

- docs/source/conf.py
Fix the RSTUF logo for repository-service-tuf.readthedocs.io
> Fix the RSTUF logo in the RTD

- CONTRIBUTING.rst
Add information for Community Meetings in the `CONTRIBUTING.rst` (which also includes to the Read The Docs).
The information about meetings will be updated on HackMD.
> Introduce the Community Meetings

- docs/source/devel/design.rst
It adds the correct stages when the API writes the TUF Repository Settings to the Development design documentation.
> doc: Scenario when API writes Repository Settings

- docs/source/guide/deployment/guide/k8s/deployment.yml
It adds a better `livenessProbe` for Redis and Postgres deployment example for kubernetes deployment.
It also removes an unnecessary `livenessProbe` used by RSTUF Worker in the example.
Closes #398
> fix: livenessProbe example in k8s guide

- CONTRIBUTING.rst
- Add a public calendar
- Move community meetings to Google Docs
- Add sprint planning meeting information
> Update RSTUF Meetings

- TAC.rst
- docs/source/devel/index.rst
- docs/source/devel/tac.rst
Empowering the participation from TUF, OpenSSF, and public repository maintainers. This initiative aims to give them a stronger voice in shaping the direction of the RSTUF project. The ultimate goal is to establish RSTUF as a neutral project with widespread benefits.
> Introducing RSTUF-TAC

- docs/source/devel/design.rst
Fix repository setting name mistake
> Fix repository setting name mistake

- .github/workflows/FT-das.yml
- .github/workflows/FT-full-signed.yml
The FT uses now the RSTUF setup scripts for running RSTUF setup during the ceremony and signing for example.
It required to run the scripts from `rstuf-umbrella/tests/` when triggered by another component repository.
These are part of setting up the RSTUF deployment for running the functional tests.
> Add GHA env variables for RSTUF setup scripts

- docs/source/devel/documentation.rst
- docs/source/devel/release.rst
This releases a new https://repository-service-tuf.readthedocs.io documentation.
It adds steps to release a new documentation version.
----
:books: Documentation preview :books:: https://repository-service-tuf--465.org.readthedocs.build/en/465/
> Add documentation release instructions

- .github/workflows/FT-das.yml
Not all components has the JoeCocker.key, but all have the JimiHendrix.key
This PR adds this common key for the step "Second Key Holder signs Bootstraps".
> fix: FT change key signing in DAS to JimiHendrix key

- tests/functional/scripts/ft-base.sh
Add to `ft-base.sh` script, which install the dependencies and CLI an option to install from source code.
It will be used by repository-service-tuf-cli component.
> Add to `ft-base.sh` option install CLI from source

- tests/functional/conftest.py
It gives a simple way to run functional tests using the TUF Client's custom metadata base URL.
The FT uses a TUF Client (python-tuf, ngclient) to verify the metadata consistency.
For some custom tests where the Metadata Base URL can have a custom address, the developer/tester can call giving an environment variable `METADATA_BASE_URL` and use it to run the tests.
> build: custom metadata base url on functional test

- tests/functional/conftest.py
It enables a possibility to run FT and not fail tests due performance.
It gives possibility to run FT to check consistency only.
> build: option to not fail FT due performance

- tests/functional/targets/test_performance.py
Add variable `PERFORMANCE` check in the BDD tests for performance. This variable, when False, disables the assert, and the test will not fail due to timeout.
The disabling performance gives the possibility to check the consistency of TUF Metadata.
> Add env var check to disable performance check

- .github/workflows/ci.yml
- .github/workflows/docs.yml
There are several documentation files in the root folder that doesn't require to trigger FT when they are changed.
Closes #505
> build: fix CI and docs workflows

- tests/functional/targets/test_add_targets.py
- tests/functional/targets/test_performance.py
- tests/functional/targets/test_remove_targets.py
The RSTUF API migrate the `/api/v1/targets` to `/api/v1/artifacts` to have a better names for the user experience.
In the TUF Specification and internals we use `Targets`, but it can be confused to RSTUF/ user.
> Migrate FT to use /api/v1/artifacts

- tests/functional/conftest.py
The `result[status]` is missing and raises an exception.
The status can be missing in early task stage
> fix: ft recurring error for test

- Makefile
- docs/source/devel/development.rst
It adds to the Makefile the commands to run the FT from the umbrella repository source code.
----
:books: Documentation preview :books:: https://repository-service-tuf--513.org.readthedocs.build/en/513/
> Enable run FT from umbrella locally

- tests/functional/bootstrap/test_bootstrap.py
- tests/functional/scripts/run-ft-das.sh
- tests/functional/scripts/run-ft-signed.sh
It adds the following changes from the API and CLI
- CLI: bootstrap updated `--upload-server` to `--api-server`
- API: `DELETE /api/v1/artifacts` to `POST /api/v1/artifacts/delete`
❗️Functionall Tests will fail
> Add breaking changes from API and CLI to RSTUF

- tests/functional/targets/test_remove_targets.py
New endpoints on RSTUF API
`DELETE /api/v1/artifacts` to `POST /api/v1/artifacts/delete`
> fix ft: new delete artifacts endpoint

- docs/source/guide/general/usage.rst
Corrects the information in the umbrella documentation for the add artifacts, and delete artifacts endpoints.
----
:books: Documentation preview :books:: https://repository-service-tuf--528.org.readthedocs.build/en/528/
> Updates the artifacts endpoints

- .gitignore
- pytest.ini
- tests/features/metadata/update.feature
- tests/functional/metadata/test_update.py
- tests/functional/scripts/rstuf-admin-ceremony.py
- tests/functional/scripts/rstuf-admin-metadata-update.py
- tests/functional/scripts/run-ft-das.sh
- tests/functional/scripts/run-ft-signed.sh
Adds interactive run of the metadata update feature and the test
implementation.
The process works by:
- It creates a thread sending "add artifacts"
- It waits for some tasks to be sent to the broker and runs the
"metadata update" request.
- It checks if the metadata update task finishes and waits to receive
more tasks and stop the thread "add artifacts"
- It validates if the new 2.root.json is in the metadata storage
- It waits for all "add artifacts" tasks to finish
- It validates if the TUF client finds all artifacts to guarantee the
consistency
This includes interactive metadata updates using the CLI to create the
the payload for `metadata update`
It will allow the future use of the DAS for metadata updates in some
scenario of FT
> tests: FT metadata update

- tests/functional/scripts/run-ft-das.sh
- tests/functional/scripts/run-ft-signed.sh
When a component triggers the FT, all generated files required by BDD tests must be in the `${UMBRELLA_PATH}` current folder. It includes:
- metadata folder (used by tuf-client)
- metadata-update-payload.json
Include pytest-xdist to improve the speed triggering the FT in parallel
> fix: ft triggered by components

- Makefile
We expect the requirements files to include the latest changes made to the Pipfile.
This does not happen since we need to lock before. This is because the `Pipfile.lock` is used to generate the requirement files, source:
https://pipenv.pypa.io/en/latest/advanced/#generating-a-requirements-txt
> fix: `make requirements` should update `Pipfile.lock`

- ROADMAP.rst
Hi folks,
We are getting close to our 1.0.0, and here is my suggestion for the final MVP roadmap.
* AWS S3 support is completed 🎉 
* Added support to add custom delegation target roles. It is important because two use cases
- Not all TUF client libraries implementation supports target hash bin delegations (TUF TAP 15).
- It will support more custom TUF repositories designs
A fantastic refactoring is going on by @lukpueh about improving the use of SecureSystemsLib (SSLib) in RSTUF. It will empower easy adoption of signers directly from SSLib. For example, it will make having HashiCorp Vault easier when enabled in the SSLib and HSM (i.e., Yubikey) signing in the RSTUF Command-Line.
* Old Metadata retention is not a `must have` for RSTUF, and Custome Delegation Roles replaced it
----
📚 …
> Updating ROADMAP for MVP

- Makefile
If we are not running `functional-tests-exitfirst` on GH actions we don't run the tests in different groups.
Related to https://github.com/repository-service-tuf/repository-service-tuf-worker/pull/493
> Add case for local running of `functional-tests-exitfirst`

- tests/functional/conftest.py
Fix ft tests.
This will make sure we return output even if we have an error.
> Fix ft tests by making sure we have an output in case of error

- tests/functional/scripts/run-ft-das.sh
- tests/functional/scripts/run-ft-signed.sh
It makes all services sharing the FT scripts from umbrella
> tests: remove custom scripts from worker

- tests/functional/scripts/rstuf-admin-metadata-sign.py
- tests/functional/scripts/run-ft-das.sh
Prepare ft tests for cli signing API communication.
I tested it with https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/579 pr locally starting tests from the CLI.
> Prepare ft tests for cli signing API communication

- docs/source/guide/deployment/setup.rst
- tests/functional/scripts/rstuf-admin-ceremony.py
- tests/functional/scripts/rstuf-admin-metadata-sign.py
- tests/functional/scripts/run-ft-das.sh
- tests/functional/scripts/run-ft-signed.sh
Update ft tests with two changes:
- use new `sign` and `ceremony` options
- bootstrap using new `admin ceremony`
> FT tests: use new `ceremony` and `sign` options & bootstrap with new `ceremony`

- tests/functional/scripts/run-ft-das.sh
- tests/functional/scripts/run-ft-signed.sh
While running the bootstrap FT it requires the ceremony-payload.json in the umbrella path, wich changes if the FT is running from umbrella or RSTUF components
> fix: ft bootstrap for components

- tests/functional/scripts/rstuf-admin-metadata-update.py
fix functional test to use the new `--out` parameter instead `-s`
It is proposed in: https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/636
> test: fix metadata update output command

- tests/functional/scripts/rstuf-admin-metadata-update.py
Add parameter `--in` to specify the root metadata
> test: add parameter `--in` to specify the metadata

- .gitignore
- Makefile
- tests/features/metadata/update.feature
- tests/functional/metadata/test_update.py
- tests/functional/scripts/run-ft-das.sh
This commit implements to the FT the test for updating the root metadata with a not fully signed metadata.
The changes are made in the `ft-das` and `Metadata Update` FT.
`ft-das` starts the DAS Bootstrap and also generates a Root Metadata Update with DAS to be used by FT.
The FT  updates the Root Metadata without all required (threshold signatures).
While signing (using the CLI), it keeps sending artifacts to the TUF metadata, which we validate as consistent.
> Ft das metadata update

- tests/functional/scripts/run-ft-signed.sh
Mising select to `continue` after added threshold number of keyes
> test: fix missing select FT Signed after added threshold

- tests/functional/scripts/run-ft-das.sh
- tests/functional/scripts/run-ft-signed.sh
It fixes the `run-ft-signed.sh` metadata update inputs/select.
It was generating an update-metadata.json without signatures.
> test: fix run-ft-signed metadata update inputs/select

- ROADMAP.rst
- tests/functional/scripts/run-ft-das.sh
These changes add to the tests of the RSTUF CLI + Worker functionality to use SaaS/Vault as an online key signing.
This FT uses a CLI interface to add the AWS KMS Key when we run the Worker tests using localstack.
----
📚 Documentation preview 📚: https://repository-service-tuf--809.org.readthedocs.build/en/809/
> tests(ft): Add the FT using AWS KMS for online key 

- tests/functional/metadata/test_update.py
fix test metadata update in the functional test to use the prompt key select file introduced to the CLI
This PR fixes the FT failing such as https://github.com/repository-service-tuf/repository-service-tuf-cli/actions/runs/12143120459/job/33859510693?pr=744
Tested locally
```log
pytest --exitfirst --splits 3 --group 3 --store-durations --durations-path=./.test_durations.3 --deselect=tests/functional/artifacts/test_performance.py tests -vvv --cucumberjson=test-report.json --durations=0 --html=test-report.html
============================================== test session starts ===============================================
platform linux -- Python 3.12.7, pytest-8.0.2, pluggy-1.5.0 -- /usr/local/bin/python3.12
cachedir: .pytest_cache
metadata: {'Python': '3.12.7', 'Platform': …
```
> test: fix ft for metadata update to use select key file

- tests/functional/metadata/test_update.py
This PR fixes the Functional Test that uses CLI and requires the settings mock object with HEADERS
> test: fix FT update metadata CLI pr #750

- docker-compose.yml
- docs/source/guide/deployment/guide/docker-compose.yml
- docs/source/guide/deployment/guide/docker.rst
- docs/source/guide/deployment/guide/k8s/deployment.yml
solves #853
Upgrades the docker containers from:
Postress 15.1 to 17.5
Both have the same vulnerability scores and none of the other images have a lower vulnerability score.
python 3.10 to 3.13
3.13 image has no identified vulnerabilities until now
redis 4.0 to 8.0
The 4.0 image had vulnerabilities while the 8.0 doesn't have any vulnerabilities until now.
Updated the docs to reflect the above changes
----
📚 Documentation preview 📚: https://repository-service-tuf--872.org.readthedocs.build/en/872/
> Updated docker images

- docs/source/guide/deployment/guide/quick-start.rst
Updated the hosts file configuration in the quick-start guide to use `127.0.0.1` instead of `$(minikube ip)`.
- Modified the hosts file entry command to use `127.0.0.1` instead of `$(minikube ip)`
- This change ensures proper routing through the Minikube tunnel for ingress resources
When using Minikube with the Docker driver, the services are exposed through the `minikube tunnel` command, which makes them available on localhost (127.0.0.1). The `minikube ip` is only accessible in the docker network and would bypass the tunnel which prevents proper access to the ingress resources.
- Verified that both `rstuf.local` and `localstack.local` are accessible after applying the changes
CC: @kairoaraujo 
----
📚 Documentation preview 📚: https://repository-service-tuf--874.org.readthedocs.build/en/87 …
> docs: Update hosts file configuration in quick-start guide

- tests/functional/artifacts/test_performance.py
- tests/functional/conftest.py
Fixes #622
The following PR simplifies the functional tests by removing the check for result[status] in the tests. Since if (state == "SUCCESS" and status == "false") => state = "ERRORED", the state variable can directly be leveraged to simplify the tests.
> Removed the use of status field in result object from functional tests

- tests/functional/artifacts/test_performance.py
Previously a [change was made](https://github.com/repository-service-tuf/repository-service-tuf/pull/877/files) in the performance test file to include a check for the `ERRORED` state, but the check for `SUCCESS` endedup being removed as well, causing the tasks not to be removed when in `SUCCESS` state in the `get_tasks` function and making them stay in the loop for longer. 
For some cases this resulted in the tests failing when running the preformance tests.
> fix: remove task when in success state
